### ISSUE TITLE
RD6024 Support

### ISSUE THREAD

**Issue by Paul-Simpson** [wildekek/riden-firmware-unisoft#1]
Hi,

Thanks for sharing this FW :)

I have a RD6024. Do I need a '24 version of the FM to make it work, or can I use the nearest version? Given there's a file for each one, I suspect the latter and if so, is this something you can provide?

Cheers, Paul

**Comment by wildekek** [comment]
Hi Paul,

I'm don't think there is RD6024 firmware yet and not sure Unifost has plans, please see his comments on the matter here:
https://www.eevblog.com/forum/testgear/ruideng-riden-rd6006-dc-power-supply/msg3974513/#msg3974513

Cheers,
Willem
